[package]
name = "d_currency_repl"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
reqwest = {version = "0.13.2", features = ["json", "blocking"]}
tokio = { version = "1.49.0", features = ["full"] }
